---
- hosts: all
  become: true
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: install pip3
      apt: name=python3-pip

    - name: ensure docker is at the latest version
      apt: name=docker.io state=latest
