---
- hosts: all
  become: true
  pre_tasks:
    - apt:
        update_cache: yes
        upgrade: yes

- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  roles:
    - web
